packages:
  - .
  - submodule/lix
  - submodule/lix/packages/js-better-sqlite3-backend
  - submodule/lix/packages/js-sdk
  - submodule/lix/packages/js-kysely
  - submodule/lix/packages/react-utils
  - '!submodule/lix/packages/**/dist'

onlyBuiltDependencies:
  - electron
  - better-sqlite3
