packages:
  - .
  - lix
  - lix/packages/js-better-sqlite3-backend
  - lix/packages/js-sdk
  - lix/packages/js-kysely
  - lix/packages/react-utils
  - '!lix/packages/**/dist'

onlyBuiltDependencies:
  - electron
  - better-sqlite3
